### ISSUE TITLE
Marker settings

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#230] opened 2020-07-06 13:56 UTC
**Describe the bug**
Strange behaviour after having fllled the markers tn the main window of NanoVNA-Saver 3.4..

**To Reproduce**

1. Connect your 2-port device , switchon NanoVNA and  startup NanoVNA-Saver.

2. Click on ''Connect to Device"
   Wait unti;l the sweep has finished.
   The marker data- AND start/stop  area in the main window have been filled with erratic data.

3. Fill in the sweep range I used  50M to 900M
   Fill the marker frequency 1 to 6  bars,  I used 50M, 100M 200M 300M 500M, 900M

4. Start the  sweep,  I had set for 20 Segments in NanoVNMA-Saver.

5. The sweep starts and fills all marker areas wiith data of MARKER 1

**Expected behavior**
Marker areas have to be filled wit data. of markers being set

**Comment by zarath** [comment] 2020-07-06 18:21
Confirmed

**Comment by zarath** [comment] 2020-07-06 19:00
Seems it only occurs in multi segment sweep

**Comment by PA3CCE** [comment] 2020-07-06 19:24
OK, I have seen many more strange data !

**Comment by zarath** [comment] 2020-07-08 12:57
Why do you have closed this bug?
It'a problem, that the position of the marker is invalid, as in segmented scan only the first of the segments is valid. After scan of that segment, it updates already some data, which triggers the markers to update.
I have to investigate a clean solution for that.

**Comment by PA3CCE** [comment] 2020-07-09 11:00
Sorry, I closed this unintentially.

**Comment by zarath** [comment] 2020-07-09 11:04
@PA3CCE 
can you try my latest development update https://github.com/zarath/nanovna-saver/tree/development

**Comment by PA3CCE** [comment] 2020-07-09 12:46
Yes I would like to, can you please send me the executable to my home address jrs@xs4all.nl, I'm not familiar to compiling in Python, sorry I should..
Jos

**Comment by zarath** [comment] 2020-07-09 13:24
I'll tell you when I've made new binaries

**Comment by zarath** [comment] 2020-07-10 10:09
https://github.com/NanoVNA-Saver/nanovna-saver/releases/tag/v0.3.5

**Comment by PA3CCE** [comment] 2020-07-10 13:38
Hi Zarath,
I downloaded and installed the new version 3.5, but sorry I can't get it connected Istarts up but when I click "Connect the device" the program aborts, the COM port is shown correctly (COM11). Version 3.4  still connects flawslesly.

**Comment by zarath** [comment] 2020-07-10 13:51
Can you look at the debug output?
Nanovna-saver.exe -D debug.txt

**Comment by PA3CCE** [comment] 2020-07-10 14:21
Commandline window says : NanoVNASaver.Hardware-Warning-Did not regognize NanVNA type from firmware.
NsanoVNA-Saver window says : "Unable to parse frequency from input start and stop fields".

**Comment by PA3CCE** [comment] 2020-07-10 15:04
This is the complete debug .txt
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4903859/debug.txt)

**Comment by zarath** [comment] 2020-07-10 15:21
I have uploaded fresh binaries. If this still fails. Please post the debug.txt again.

**Comment by PA3CCE** [comment] 2020-07-10 15:29
OK

**Comment by PA3CCE** [comment] 2020-07-10 16:13
I downloaded the executable from the same link and executed it. The program loaded with the same error "could not parse Start and Stop frequency".
I saw that the start frequency was 50k and the stop freq 50.2k so a span of 200 Hz, Segments was set to 20, since the program on a H4 sets to ro 201 points it calculates correctly a step of (200/20)/201 = 49.75 mHz, imho THIS IS THE PROBLEM. !!
I attached the new debug.txt
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4904199/debug.txt)

**Comment by PA3CCE** [comment] 2020-07-10 16:34
I downloaded the file from the old link (above) did I realy get the updated version ? the warning in the command window is still the same also ! The program still aborts when I fill in more reasonable frequencies.

**Comment by zarath** [comment] 2020-07-10 16:37
if it detects -H4 as NanoVNA it is the right one..
Technically it is impossible to run steps below 1 Hz, as Frequencies are transfered as integers.
Can you try Span of 100M or so?

**Comment by PA3CCE** [comment] 2020-07-10 18:49
A setting for mHz per step is impossaible ofcourse, so this must be prohibited I think.
Before dinner I had set for a sweep 50MHz to 2GHz, when I pressed "Sweep"the program aborted.
When I came back the program starts up normally, no error messages, when I press "Connect to device" the program aborts after 1 or 2 seconds as before.

**Comment by PA3CCE** [comment] 2020-07-10 19:25
The last message was when I started NanoVNA-Saver normally.
Now I started NanoVNA-Saver from the command prompt and got the errormessage from NanoVNA-Saver "Unable to parse frequencies" again,  no error- or warning messages in the command window..... Then when I set for 50M to 2G sweep the program aborts after pressing sweep.

**Comment by zarath** [comment] 2020-07-10 19:29
Is the -H4 really capable of 2GHz?

**Comment by PA3CCE** [comment] 2020-07-10 19:37
Yes can go upto 2.7GHz

**Comment by PA3CCE** [comment] 2020-07-10 19:40
Much more noise ofcourse, but it accepts.

**Comment by PA3CCE** [comment] 2020-07-10 19:54
On the high end you'd better use 10 Hz bandwidth and averaging, taking much time. But can be done. (less accurate ofcouse).

**Comment by igor-m** [comment] 2020-07-11 08:16
There is a difference v034 vs. v035 - it seems there is a bug in v035vcalculation somewhere. Here is the v034 and v035 with the same settings and connected to an H-4 terminated with stock coax and stock 50ohm load.
![v034](https://user-images.githubusercontent.com/7240123/87219905-7d512200-c35f-11ea-8744-c54aa39879f7.PNG)
![v035](https://user-images.githubusercontent.com/7240123/87219906-7de9b880-c35f-11ea-9bda-f6ccdb8c55ef.PNG)

**Comment by PA3CCE** [comment] 2020-07-11 13:43
Hi igor-m,
How did you manage to run NanoVNA-Saver v 3.5 ? With me it aborts when pressing  "Connect to device".
My system Windows 10.

**Comment by PA3CCE** [comment] 2020-07-11 13:47
Igor-m,
I think you are not using NanoVNA-H4.

**Comment by zarath** [comment] 2020-07-11 14:07
@PA3CCE i have changed the binaries again. At least the crash should now be recorded in debug log
so nanovna-saver.exe -D debug.txt should give more information why ...

**Comment by igor-m** [comment] 2020-07-11 15:41
@PA3CCE - indeed, I've been using H4. Now freshly flashed with DiSlord's 0847fw (works great on the first glance, the latest fw release before the 09xxfw "SDcard" ones). The saver v035 was broken somehow, now the v036pre seems to work better. Zarath does a great job!

**Comment by PA3CCE** [comment] 2020-07-11 16:12
OK Zarath and and igor-m, I will have dinner first and then will download and run the new upload..... igor-m I'm using latest firmware from DiSlord V0.9.3.1.

**Comment by PA3CCE** [comment] 2020-07-11 18:08
I downloaded and ran the new uploaded version 3.5. The program still aborts when I press "Connect to device". Attached the new debug.txt.
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4907391/debug.txt)

**Comment by PA3CCE** [comment] 2020-07-11 18:22
The problem appears to be in statement exec_command(data 0),  after reading VNA data 0.

**Comment by igor-m** [comment] 2020-07-11 19:57
@PA3CCE - the 09xx fw is for H4 with SDcard mounted, afaik. Also you want the "v036-pre" to get better results, as I wrote above..

**Comment by PA3CCE** [comment] 2020-07-11 21:36
@ igor-m......Yes I have installed a SDcard slot and a clock X-tal and it works very well stand-alone on my NanoVNA-H4.....I just found that there is a version 0.9.3.4 firmware by DiSlord,......I missed that....I just downloaded it and will flash it,  will see what happens....I think it has minor updates.....On the link Zarath gave me I do not find version 0.3.6-pre of NanoVNA-Saver.

**Comment by PA3CCE** [comment] 2020-07-11 21:59
Just flashed the latest firmware 0.9.3.4 by DiSlord and ran NanoVNA-Saver from command prompt, same problem NanoVNA-Saver latest version 3.5 aborts after "Connect to device" .
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4907660/debug.txt)

**Comment by RandMental** [comment] 2020-07-13 06:07
I ran the latest NanoVNA-Saver last night, also with 0.9.3.4 firmware on the H4, had no problems with the USB  connecting and using Saver. 
-------- Original message --------From: PA3CCE <notifications@github.com> Date: 2020/07/12  00:00  (GMT+02:00) To: NanoVNA-Saver/nanovna-saver <nanovna-saver@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [NanoVNA-Saver/nanovna-saver] Marker settings (#230) 
Just flashed the latest firmware 0.9.3.4 by DiSlord and ran NanoVNA-Saver from command prompt, same problem NanoVNA-Saver latest version 3.5 aborts after "Connect to device" .
debug.txt

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NanoVNA-Saver/nanovna-saver/issues/230#issuecomment-657136602",
"url": "https://github.com/NanoVNA-Saver/nanovna-saver/issues/230#issuecomment-657136602",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zarath** [comment] 2020-07-13 08:33
@RandMental was it the v0.3.6-pre version from last midnight?

If yes, I've made a binary here, so @PA3CCE can check
https://github.com/NanoVNA-Saver/nanovna-saver/releases/tag/v0.3.6

**Comment by RandMental** [comment] 2020-07-13 08:54
Hi Holger 

 

Attached is my Debug.txt – I do not have any problems with either 0.3.5 or 0.3.6 Pre to connect and function as required.  Could not duplicate the retries seen by PAC

 

Here is the 0.3.6 debug file – only problem here is that it does not read the  Start and End frequencies from the device on start-up, I guess you have hard-code it to 27 and 30MHz

**Comment by igor-m** [comment] 2020-07-13 10:46
Marker settings issue with latest 036pre - when I set Markers to certain fixed values (ie 1-30, 2-100, 3-300 MHz) and do sweep (10 segments from START to 500MHz) while changing the START frequency (START always below 30MHz, like 2-15MHz) some Markers (usually Marker1, but others too) change its value off expected range (for example 1-4.2MHz, 3-386MHz). Below a debug.txt from such a session, if that helps.
[debug_Markers.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4911911/debug_Markers.txt)

**Comment by PA3CCE** [comment] 2020-07-13 11:41
@Zarath ....I downloaded and installed Nan0VNA-saver V 3.6 pre..... In the mean time I have upgraded to DiSlord's lastest version firmware V 0.9.3.4. ...Sorry,  I still have the same problem,....NanoVNA-Saver loads correctly but whe I press "Connect to device" the sweep starts but after a few seconds the program aborts....., I tried in Windows 10 directly and from a command prompt as well (same result).
Below the debug.txt file

[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4912157/debug.txt)

**Comment by PA3CCE** [comment] 2020-07-13 12:07
@Zarath... After reading the debug file I can see that the problom occurs in the first segment of scanning (36 retry's) and processing the data (to many retry's) of a segmented scan.

**Comment by igor-m** [comment] 2020-07-13 12:29
The crash with latest 036pre happens here as well sometimes. It seems the success depends on the internal state of the H4.  Try to OFF/ON the H4 before you click Connect.

**Comment by PA3CCE** [comment] 2020-07-13 12:29
@Zarath....After reading the debug file of RandMental I think the problem is in the sweeprange/segments setting, I used the default setting and 20 sgments... RandMental had set to a different range and 2 segments only..  Nevertheless RandMental had 10 retry's in reading the first data, but could finish the scan.

**Comment by zarath** [comment] 2020-07-13 12:31
strange, that it tooks so long to get data from your vna...

After scan command it tooks some time until actual data is delivered... My current retry value was 40 (times 50ms = 2seconds)
I've made a 100times retry one (5 seconds)

**Comment by zarath** [comment] 2020-07-13 12:34
@PA3CCE heaving retries is normal, I do repetitve reads to get the data as soon as possible. 10 means, that it only took 0.5seconds after the scan started until data was ready.

**Comment by igor-m** [comment] 2020-07-13 12:41
FYI - enclosed are some logs where it crashed here. 

[debug_ERR1.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4912460/debug_ERR1.txt)
[debug_ERR3.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4912462/debug_ERR3.txt)
[debug_ERR2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4912463/debug_ERR2.txt)

**Comment by PA3CCE** [comment] 2020-07-13 12:44
I tryed many times to start normally from windows but program aborted always, even when I had set for a different sweeprange before I pressed "Connect to device". @ Zarath Maybe because I had set to 20 segments Nan0VNA-Saver needed more time ?
Just I guess.

**Comment by PA3CCE** [comment] 2020-07-13 12:59
I tried many times to set NanoVNA on/off , always crashes".... now I found it crashes when I press "Sweep Settings" as well, not for the other buttons. I can see that Igor-m's scans run much longer, probably there are more criterea for a crash ?

**Comment by PA3CCE** [comment] 2020-07-13 13:15
I started NanoVNA-Saver from the command prompt, pressed "Sweep Settings",  the command window showed ..................................              Traceback ((most recent call last):
  File "NanoVNASaver\widgets\SweepControl.py", line 92, in <lambda>
  File "NanoVNAsAver\NanoVNASaver.py", line 779, in display_window
KeyError: ''settings

Attached Debug2.txt
[debug2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4912663/debug2.txt)

**Comment by RandMental** [comment] 2020-07-13 13:53
I have now increased the segments also to 20 and then back to 10.

All works fine on the -H4 0.9.3.4 LSE

 

It now don’t crash in Calibration anymore,  but when I tried to Save the calibration data (10 segments) 

 

regards

**Comment by igor-m** [comment] 2020-07-13 14:05
@RandMental - a hint: you may attach your debug.txt file into your message by dragging and dropping..

**Comment by PA3CCE** [comment] 2020-07-13 14:23
@ RandMental ....Very strange, I'm running NanoVNA-H4 on DiSlord's version 0.9.3.4 on NanoVNA-Saver 3.6 pre as well and can't get it connected, ....It crahes while doing the initial sweep on the default settings....Switching the device on and off before does not help.

**Comment by zarath** [comment] 2020-07-13 14:37
> FYI - enclosed are some logs where it crashed here (latest 036pre, H4-0847fw, Win10, 10Segments).
> 
> [debug_ERR1.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4912460/debug_ERR1.txt)

Validation Error.

Sorry I have no clue why Rune had added an exception if a data value is out of an arbitrarily range.
The value was raised several times.. I don't know if there was a discussion about set setting in the early state of the software...

**Comment by RandMental** [comment] 2020-07-13 14:54
Correction - calibration still fails with a crash when clicking Apply  after the Wizard finished the SOL calibration sequence.   10 Segments by 201 points sweep selected

 

Debug attached

 

regards

 

From: randmental@gmail.com <randmental@gmail.com> 
Sent: 13 July 2020 15h54
To: 'NanoVNA-Saver/nanovna-saver' <reply@reply.github.com>; 'NanoVNA-Saver/nanovna-saver' <nanovna-saver@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>; 'Holger Müller' <holgerm1969@gmx.de>
Subject: RE: [NanoVNA-Saver/nanovna-saver] Marker settings (#230)

 

I have now increased the segments also to 20 and then back to 10.

All works fine on the -H4 0.9.3.4 LSE

 

It now don’t crash in Calibration anymore,  but when I tried to Save the calibration data (10 segments) 

 

regards

**Comment by PA3CCE** [comment] 2020-07-13 16:22
NanoVNA-Saver 3.6 pre freezes when started from scratch
=====================================

**Closed** 2020-07-15 17:54 UTC
Labels: bug
