### ISSUE TITLE
Band Sweeps, missing band, limits incorrect

### ISSUE THREAD

**Issue by ricknun** [NanoVNA-Saver/nanovna-saver#351] opened 2020-11-19 17:47 UTC
**Describe the bug**
For band sweeps in the United States, the 1.25m band is missing and other bands have incorrect limits.

**To Reproduce**
Sweep Settings, Select Band (no 1.25m choice), 2 m, None (see 144.0 to 146.0 MHz).

**Expected behavior**
The 1.25m band (222 to 225 MHz) should be given as an option.  In the United States the 2m band is 144 to 148 MHz, not 144 to 146.  (There are other similar issues. See below.)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - NanoVNA-Saver version: 0.3.8

**Additional context**
There are other United States band limit errors too, for example 80m should be 3.5 to 4.0 MHz, not 3.5 to 3.8. I suggest providing some way to make all bands and band limits agree with http://www.arrl.org/graphical-frequency-allocations.  This could be done by letting the user set a list of bands and limits, to be remembered through program exit and re-start. Then the user could also decide and set "padding" outside the bands case-by-case instead of having to choose one of the few % padding limits provided now.

**Comment by zarath** [comment] 2020-11-19 17:55
Duplicate of #257

**Closed by zarath** 2020-11-19 17:55 UTC
