### ISSUE TITLE
NanoVNA- 3.7 rc07 aborts at "connecting device"

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#295] opened 2020-07-29 11:20 UTC
I  Downloaded version 0.3.7 rc07 from Github-development and installed it.
When I press "Connect to device"the program aborts,  even after removing the NanoVNASaver depository from C: drive.

[debug_rc07.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4994540/debug_rc07.txt)

**Comment by zarath** [comment] 2020-07-29 11:40
Duplicate of #286 
test pre08

**Closed by zarath** 2020-07-29 11:40 UTC
Labels: duplicate
