### ISSUE TITLE
NanoVNA-Saver 3.6 pre freezes when started from scratch from scratch

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#244] opened 2020-07-13 16:54 UTC
**Describe the bug**

When You install NanoVNA_saver 3.6 pre from scratch, the program starts-up,...When you click on " Connect to device" the program freezes.

**To Reproduce**

1.  When you had NanoVNA_Saver earlier installed, delete the program.
     Goto C:/Users/yourname/appdata/Roaming and delete repository "NanoVNA_Saver"
2.   Download NanoVNA-Saver 3.6 pre and install.
3.   Run NanoVNA-Saver and answer question about update.
4.   Press "Manage" button and deactivate the default "Validate received data"  (Seems to create an abort).
5.  Press "Connect to device".
6. The program freezes. (Important for new users !!!!)

**Expected behavior**
The program connects to the device and is ready to be used.

**Desktop (please complete the following information):**
 - OS:  Windows 10 Home edition (fully updated).
 - NanoVNA-Saver version: 3.6 pre.
 - NanoVNA-H4 with DiSlord's firmwaware V 3.9.4 SLE (with SSD slot and clock X-tal).

**Additional context**
After a lot of problems I wanted to start from scratch.

**Comment by igor-m** [comment] 2020-07-13 17:18
I've done as per your above steps.
It works here (H4 0847fw).
This is what I see after I've clicked on Sweep (H4 CH0 terminated by the stock load).
![Fresh start](https://user-images.githubusercontent.com/7240123/87333536-88fa3f80-c53d-11ea-8037-a836d1a84361.PNG)

**Comment by PA3CCE** [comment] 2020-07-13 19:36
@ Igor-m....If I understand well, you are using different firmware (0847fw)....Did you try DiSlord's latest firmware ? it's very good !!!, Different firmware might cause different results.

**Comment by igor-m** [comment] 2020-07-13 19:55
I did with 0847fw (the latest pre-SDcard one), but there is an another issue I cope with, so I downgraded to 0846fw - the same, now I test 0845 firmware. I do not want go to the 09xx as it is much more complex (sdcard etc). I want to see a stable operation first..

**Comment by PA3CCE** [comment] 2020-07-13 21:03
OK I see, well with me,  with my firmware,  NanoVNA-Saver old versions (before 3.5) worked well but without the ectra's in the firmware............. I just started the program from window's command prompt to produce a debug.txt file......To my surprise it connected flawlessly and the screen was as yours. ....When I looked for a debug.txt file, there was'nt one .........Because the program started and connected correctly from the prompt, I tried to start and connect the program normally (not from the prompt) and it connected correctly as well....Then I set for a scan of 50M to 900M  and 20 segments and loaded a corresponding calibration file.... This caused an abort of the program (I had a BiasTee connected between CH0 and CH1)....I went back to starting the program from the prompt and now the program aborted after pressing "Connect to the device".... This time I found the debug.text file as attached.................I'm getting frustrated. 
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4915069/debug.txt)

**Comment by igor-m** [comment] 2020-07-13 21:38
Do not be frustrated.. Everything is beta here :) At the end of the day it will work fine, indeed, as the talented people mess with debugging those betas :)

**Comment by zarath** [comment] 2020-07-13 21:44
Some of your crashes should be fixed in latest source code. It is time consuming for me to create a binary on every patch.  As the process of building isn't fully automatic yet

**Comment by igor-m** [comment] 2020-07-14 06:59
You may test without binaries in Linux, for example. Here is Ubuntu in VirtualBox (Win10) running 036-pre Development branch..
![Development branch 036-pre in Ubuntu 18_04](https://user-images.githubusercontent.com/7240123/87394670-5fc6c700-c5b0-11ea-9908-08a80737b747.PNG)

**Comment by PA3CCE** [comment] 2020-07-14 08:05
OK, I will wait for new binaries.

**Comment by PA3CCE** [comment] 2020-07-14 08:16
@ igor-m Yes I know very well this is beta and for the frustation : I was joking.

**Comment by zarath** [comment] 2020-07-14 10:20
@PA3CCE 

fresh binaries! .. Some of your issues could be due to bandwidth settings of nanovna. If your device is in bandwidth 10 mode, it took exponential longer to scan the data, compared to bandwidth 1000 (the default)

As there is no way to read out current setting from the vna, I now set the bandwidth to 1000 on connect.
But now you can select possible values in the device setting dialog.

Hope you have more luck with v0.3.6-rc now

**Comment by PA3CCE** [comment] 2020-07-14 10:58
For your info :  This morning I deleted the NanoVNA-Saver repository from Windows C: drive (The program itself is installed on my D: drive)....Then tried starting the program normally from Windows.... The first time it aborted immediately,... The second time it started up and I could connect, set sweeprange to 50 to 900MHz 1 segment only and run with reasonable result.....Then I tried to load a calibration file  made by NanoVNA-Saver version 3.4,  this caused the program to abort.

**Comment by zarath** [comment] 2020-07-14 11:10
debug.txt?

**Comment by RandMental** [comment] 2020-07-14 11:23
I cannot build 0.3.6 in your dev branch

 

Traceback (most recent call last):

  File "C:\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Python\Python38\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Workspaces\nanovna-saver-z\NanoVNASaver\__main__.py", line 88, in <module>

    main()

  File "C:\Workspaces\nanovna-saver-z\NanoVNASaver\__main__.py", line 80, in main

    window = NanoVNASaver()

  File "C:\Workspaces\nanovna-saver-z\NanoVNASaver\NanoVNASaver.py", line 87, in __init__

    self.sweep_control = SweepControl(self)

TypeError: 'module' object is not callable

**Comment by igor-m** [comment] 2020-07-14 11:25
While running your 036rc exe

`NanoVNASaver 0.3.6-rc

Copyright (C) 2019, 2020 Rune B. Broberg
Copyright (C) 2020 NanoVNA-Saver Authors

This program comes with ABSOLUTELY NO WARRANTY
This program is licensed under the GNU General Public License version 3

See https://github.com/NanoVNA-Saver/nanovna-saver for further details.

Settings: C:/Users/pito/AppData/Roaming/NanoVNASaver/NanoVNASaver.ini
Traceback (most recent call last):
  File "nanovna-saver.py", line 24, in <module>
  File "NanoVNASaver\__main__.py", line 80, in main
  File "NanoVNASaver\NanoVNASaver.py", line 87, in __init__
TypeError: 'module' object is not callable
[170552] Failed to execute script nanovna-saver`

**Comment by igor-m** [comment] 2020-07-14 11:27
NanoVNASaver 0.3.6-rc

Copyright (C) 2019, 2020 Rune B. Broberg
Copyright (C) 2020 NanoVNA-Saver Authors

This program comes with ABSOLUTELY NO WARRANTY
This program is licensed under the GNU General Public License version 3

See https://github.com/NanoVNA-Saver/nanovna-saver for further details.

Settings: C:/Users/smith/AppData/Roaming/NanoVNASaver/NanoVNASaver.ini
Traceback (most recent call last):
  File "nanovna-saver.py", line 24, in <module>
  File "NanoVNASaver\__main__.py", line 80, in main
  File "NanoVNASaver\NanoVNASaver.py", line 87, in __init__
TypeError: 'module' object is not callable
[170552] Failed to execute script nanovna-saver

**Comment by RandMental** [comment] 2020-07-14 11:28
Ditto

 

Something broke ----

 

C:\Python\Python38\python.exe -m NanoVNASaver.__main__ -D debug.txt

NanoVNASaver 0.3.6-rc

 

Copyright (C) 2019, 2020 Rune B. Broberg

Copyright (C) 2020 NanoVNA-Saver Authors

 

This program comes with ABSOLUTELY NO WARRANTY

This program is licensed under the GNU General Public License version 3

 

See https://github.com/NanoVNA-Saver/nanovna-saver for further details.

 

Settings: C:/Users/deond/AppData/Roaming/NanoVNASaver/NanoVNASaver.ini

Traceback (most recent call last):

  File "C:\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "C:\Python\Python38\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Workspaces\nanovna-saver-z\NanoVNASaver\__main__.py", line 88, in <module>

    main()

  File "C:\Workspaces\nanovna-saver-z\NanoVNASaver\__main__.py", line 80, in main

    window = NanoVNASaver()

  File "C:\Workspaces\nanovna-saver-z\NanoVNASaver\NanoVNASaver.py", line 87, in __init__

    self.sweep_control = SweepControl(self)

TypeError: 'module' object is not callable

 

Process finished with exit code 1

**Comment by zarath** [comment] 2020-07-14 11:31
Pushed missing __init__.py

**Comment by RandMental** [comment] 2020-07-14 11:51
I get now that Saver crash when connected  -

**Comment by zarath** [comment] 2020-07-14 12:00
> For your info : This morning I deleted the NanoVNA-Saver repository from Windows C: drive (The program itself is installed on my D: drive)....Then tried starting the program normally from Windows.... The first time it aborted immediately,... The second time it started up and I could connect, set sweeprange to 50 to 900MHz 1 segment only and run with reasonable result.....Then I tried to load a calibration file made by NanoVNA-Saver version 3.4, this caused the program to abort.

strange that v0.3.6-rc binary runs any way.  current should

**Comment by igor-m** [comment] 2020-07-14 12:02
Crashes here as well when trying to connect (running 036-rc from your development branch).

**Comment by zarath** [comment] 2020-07-14 12:15
strange that there is no backtrace .. 
I assume an -H or -H4 version .. 
can anyone use a terminal and issue an naked bandwidth command?

ch>bandwidth

and paste me the result?

**Comment by igor-m** [comment] 2020-07-14 12:17
self.set_bandwidth(self.get_bandwidths()[-1])
IndexError: list index out of range

**Comment by igor-m** [comment] 2020-07-14 12:22
NanoVNA Shell
ch> bandwidth

no result..

**Comment by zarath** [comment] 2020-07-14 12:24
> NanoVNA Shell
> ch> bandwidth
> 
> no result..

daf*q

**Comment by RandMental** [comment] 2020-07-14 12:27
Hi Holger

Both H1 and H4

 

ch> bandwidth                                                                   

bandwidth 1 (1000Hz)                                                            

ch>

**Comment by igor-m** [comment] 2020-07-14 12:31
ch> bandwidth

bandwidth 1 (1000Hz)

(LF/CR problemm :) )

**Comment by zarath** [comment] 2020-07-14 12:43
did i told that i hate dos linebreaks :-)

**Comment by zarath** [comment] 2020-07-14 12:44
plain bandwidth do return something ?
or not?

**Comment by RandMental** [comment] 2020-07-14 12:54
Below Sequence RED is me typing, black is what comes back

 

CRLFCH>  bandwidthCRLFbandwidth 1 (1000Hz)CRLFCH> 

 

Note there is a space adter each “>” character

**Comment by RandMental** [comment] 2020-07-14 13:08
Hallo Holger 

 

The Device now stops sweeping for its own display – seems to hang, but when ones click on Saver -> Sweep, then it does respond.

 

Regards

**Comment by igor-m** [comment] 2020-07-14 13:08
:)
![Fresh 036rc](https://user-images.githubusercontent.com/7240123/87429318-e5179f00-c5e3-11ea-97c9-19709221116b.PNG)

**Comment by zarath** [comment] 2020-07-14 13:20
> Hallo Holger The Device now stops sweeping for its own display – seems to hang, but when ones click on Saver -> Sweep, then it does respond. Regards 2020-07-14 14:28:34,152 - NanoVNASaver - INFO - Startup... 2020-07-14 14:28:34,223 - NanoVNASaver.SweepWorker - INFO - Initializing SweepWorker

seems not to be the latest commit, as i now should see the sequence:
2020-07-14 15:15:47,232 - NanoVNASaver.Hardware.Hardware - INFO - Finding firmware variant...      
2020-07-14 15:15:47,335 - NanoVNASaver.Hardware.Hardware - DEBUG - Needed retries: 0                                                                                                                            
2020-07-14 15:15:47,335 - NanoVNASaver.Hardware.Hardware - INFO - Type: Generic NanoVNA    
during connect to device

**Comment by igor-m** [comment] 2020-07-14 13:29
I need a bit larger display :)
![Fresh 036rc 9 Markers Part I](https://user-images.githubusercontent.com/7240123/87431310-bcdd6f80-c5e6-11ea-95d4-abda0e53aba1.PNG)
![Fresh 036rc 9 Markers Part II](https://user-images.githubusercontent.com/7240123/87431322-bfd86000-c5e6-11ea-88c3-160a6b49c9d2.PNG)

**Comment by zarath** [comment] 2020-07-14 13:32
4k is the way to go :100:

**Comment by zarath** [comment] 2020-07-14 13:34
I don't remember if I had defined a upper limit for the number of markers ...

**Comment by PA3CCE** [comment] 2020-07-14 15:28
@ Zarath........ I downloaded your new version 3.6 rc and installed it in a new repository (deleted the old one) on my D: drive........Deleted the NanoVNA repository from the C: drive....... Started NanoVNA-Saver 3.6 rc from it's repository........ The program started up........ Pressed  "Connect to device"....... The program aborted........ Tried 5 times !!!.,......Then I started the program from Window's command prompt.........The program started up..........Pressed  "Connect to device" ........ The program aborted (tried twice).......,....A repository NanoVNASaver was created on the C: drive  with NanovnaSaver.ini,  no Bands.ini..........Debug.txt is attached
I could not attach the .ini file because here .ini is not supported so I changed it into NanoVNASaver.txt 

[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4919583/debug.txt)
[NanoVNASaver.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4919634/NanoVNASaver.txt)

....... The command-window did not abort and ended with :

Settings : C:/Users/jrs/AppData/Raoming/NanovnaSaver/NanoVNASaver.ini
Traceback (most recent call last) :
  File "NanoVNASaver\NanoVNASaver.py", line 519, in serialButtonClick
  File "NanoVNASaver\NanoVNASaver.py", line 541, in connect_device
  File "NanoVNASaver\Hardware\Hardware.py", line 90, in get_VNA
  File "NanoVNASaver\Hardware\VNA.py", line52, in __init__
Indexerror: List index out of range

**Comment by igor-m** [comment] 2020-07-14 16:12
@PA3CCE - based on your debug file you are trying to run the version 036-pre.
You should run 036rc instead..

**Comment by PA3CCE** [comment] 2020-07-14 18:37
@ igor-m.... Thanks for your warning...., I checked my upload and it is from the 3.6 pre...., I must have picked the file from the wrong repository......I checked the debug file in the correct repository and it shows 3.6 rc, Sorry abt that. I attached the correct file here.

**@** **Zarach...Vy** **sorry** **I** **attached** **the** wrong **debug** file **in** **my** **previous** **message,** **The** **correct** **file** is attached **here.**

**[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4920523/debug.txt)**

**Comment by igor-m** [comment] 2020-07-14 19:16
@PA3CCE - where your repository with 036-rc comes from?

**Comment by PA3CCE** [comment] 2020-07-14 19:37
@igvor-m ....... I don't quite understand why you ask,..... I downloaded the .zip file from Github and extracted in a new repository on my D: drive in a newly created repository called NanoVNA-Sver 3.6 Release Candidate..... That's all.

**Comment by igor-m** [comment] 2020-07-14 19:52
Where from Github did you download the zip file?

**Comment by PA3CCE** [comment] 2020-07-14 20:19
From the develment branch released by Zarach 9 hours ago.

**Comment by zarath** [comment] 2020-07-14 20:25
@PA3CCE 
it's not the latest

I see it in the hardware detection.

Do you have an -H -H4 variant, too?

Latest is https://github.com/NanoVNA-Saver/nanovna-saver/releases/tag/v0.3.6

**Comment by PA3CCE** [comment] 2020-07-14 20:30
@ igor-m.... I only have the -H4..... Your link directs me to the one I downloaded !!!

**Comment by zarath** [comment] 2020-07-14 20:40
Exactly this? https://github.com/NanoVNA-Saver/nanovna-saver/releases/download/v0.3.6/NanoVNASaver.windows-latest.zip

**Comment by igor-m** [comment] 2020-07-14 20:42
> 
> 
> @ igor-m.... I only have the -H4..... Your link directs me to the one I downloaded !!!

@PA3CCE: I have not provided any link to you.. I've been just asking you kindly to tell us where did you download the repository from, and I do it for some time already :)

**Comment by zarath** [comment] 2020-07-14 20:47
the freeze occurs as H4 didn't respond with possible bandwidth settings to a plain bandwidth command.
Original NanoVNA tells about possible settings if that command is called without parameters.
In current version I cannot do bandwidth settings for -H versions ... :-(
That's the current workaround.
I -H4 is able to do a bandwidth equivalent to 10 as in the original NanoVNA and is set to this at connection, i expect  trouble...
:-(
And as long as I didn't find the current source of DiSlords patches I cannot reverse engineer the behaviour of -H versions.

**Comment by PA3CCE** [comment] 2020-07-14 20:49
@ igor-m.....Oh sorry it was from zarath....., I expected response from you.... Zarath commented the it was not the latest and gave me a link that directed me to the one I downloaded.

@Zarath the link you gave me first was directing me to the one I downloaded.....The second one does not work, it tries to connect but it aborts.

**Comment by zarath** [comment] 2020-07-14 20:53
PA3CCE can you try to install from source......
it's just installing python from the microsoft store and then follow the installation instructions in the readme

**Comment by PA3CCE** [comment] 2020-07-14 21:07
@Zarath.....The first link you gave me was ok it directed me exactly to where I downloaded the NanoVNASaver.windows-latest.zip file.
I have Python 3.7 and 3.8.3 installed on my D: drive but really dont know how exactly to compile your source files, vy sorry.

**Comment by zarath** [comment] 2020-07-14 21:09
Nothing to compile. Python is an interpretated language

**Comment by PA3CCE** [comment] 2020-07-14 21:16
OK, I understand, in the very past I have worked with interpreters and Pascal programming, but I installed Python but was too busy with other things to study how to work with it.... It's getting rather late now, so I would continue tomorrow if you don't mind.

**Comment by PA3CCE** [comment] 2020-07-14 21:34
@ Zarath.... I just read your comments abt the bandwith settings, For your info, I only use the -H4 version and the bandwith setting was 100 Hz.... See you tomorrow if you are here.... Good night to you and igor-m.

**Comment by PA3CCE** [comment] 2020-07-15 10:29
@Zarath  I foud your message with the second link to the last version of NanoVNA-Saver in my e-mail as well. From there I was able to download the Windows.zip file. I'm sure that I had the correct one, but I will install the program again from this last download and the run it with the bandwidth set to 1kHz,  will let you know the result.

**Comment by PA3CCE** [comment] 2020-07-15 12:03
@Zarath...NanoVNA -H4 to  ON.... Device set to Bandwidth 1kHz....Deleart/stopted  repository NanoVNASaver from C: drive:.... Deleted NanoVNA-Saver 3.6 rc from my D: drive. ....Re-installed NanoVNA-Saver 3.6 rc from the **last** download...... Opened a  Command Window.....In command window went to repository  NanoVNA-Saver 3.6 rc on my D: drive..... executed nanovna-saver.exe -D debug.txt....Program showed up with empty start/stop and 1 segments, Com port: Com11..... pressed "Connect to device"...........One sweep was performed......Segments set to 10......Start/stop set to 50MHz/2GHz....., Segments set to 10................Sweeps were performed correctly with resonable results......Loaded a corresponding calibration file made by version 3.4.......PROGRAM ABORT ! .......Searched for debug.txt file, not present in NanoVNA-Saver 3.6 rc repository..........Command window (not aborted) shows at the end :

Settings: C:/users/jrs/AppData/Roaming/NanoVNASaver/NanoVNA.ini
Traceback most recent (call last):
File "NanoVNASaver\Windows\CalibrationSettings.py", line 118, in <lambda>
File "NanoVNASaver\Windows\CalibrationSettings.py", line 575, in loadCalibration
File "NanoVNASaver\Windows\CalibrationSettings.py", line 455, in calculate
AttributeError: 'NanoVNASaver' oblect has no attribute 'btnStopSweep'

Will do some more testing

**Comment by PA3CCE** [comment] 2020-07-15 12:05
@Zarath Sorry in the first line "Deleart/stopted" must be "deleted"

**Comment by PA3CCE** [comment] 2020-07-15 12:31
@Zarath...After the above,  in the command window "nanovna-saver.exe -D debug.exe" does start the program but clicking "Connect to device"  causes freezing of the program, like it did before using the old installation, even after deleting the .ini file on the C; drive. 

What has changed where ??

**Comment by zarath** [comment] 2020-07-15 12:59
freeze is caused by bandwidth detection. It's different between ttrfech's and dislord's firmware.

I've flashed my nanovna with current dislords one and hopefully fixed it in -rc1

**Comment by PA3CCE** [comment] 2020-07-15 13:05
OK, it's clear to me, in the rc phase you have to de- re-install the program after aan error.

**Comment by zarath** [comment] 2020-07-15 13:16
that shouldn't be necessary

**Comment by PA3CCE** [comment] 2020-07-15 13:24
No, but they are pre releases so you can expect problems. I will go on testing and avoid downloading old calibrations. until the next problem HI

**Comment by PA3CCE** [comment] 2020-07-15 13:56
Deleted repository NanoVNA-Saver 3.6 rc.......Downloaded and installed NanoVNA-Saver 3.6 rc1........Started it from Windows command prompt........ Program popped up..... Pressed "Connect to device" ........Program freezed !!!..... What say ?

**Comment by zarath** [comment] 2020-07-15 13:58
nothing without debug.txt

**Comment by PA3CCE** [comment] 2020-07-15 14:01
Can't produce, because program freezed, had to force exit Windows.

**Comment by PA3CCE** [comment] 2020-07-15 14:04
Command window stayed open, but didi not report errors.

**Comment by zarath** [comment] 2020-07-15 14:06
.exe -D debug.txt should always deliver data. regardless how the program terminates

**Comment by PA3CCE** [comment] 2020-07-15 14:08
OK, will try.

**Comment by PA3CCE** [comment] 2020-07-15 14:14
Ok, you are right, below debug.txt, didn't read it myself.
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4925776/debug.txt)

**Comment by PA3CCE** [comment] 2020-07-15 14:17
Doesn't tell much.

**Comment by zarath** [comment] 2020-07-15 14:20
fun fact. it freezes where i haven't changed anything----

in the info command.

**Comment by PA3CCE** [comment] 2020-07-15 14:22
strange

**Comment by PA3CCE** [comment] 2020-07-15 14:33
You did not change , but the previous version did the same with me, so that's logic.

**Comment by PA3CCE** [comment] 2020-07-15 14:34
Could it be the comport speed, I checked and it is set to 12800 bps

**Comment by PA3CCE** [comment] 2020-07-15 14:42
Have set to 9600 bps, same thing.

**Comment by PA3CCE** [comment] 2020-07-15 14:55
Device itself is frozen when NanoVNA-Saver is running no more, needs ON/OFF then the program does not freeze but then it aborts, will do it again and make a debug file.

**Comment by PA3CCE** [comment] 2020-07-15 15:01
Herewith debug2.txt
[debug2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4926037/debug2.txt)

**Comment by PA3CCE** [comment] 2020-07-15 15:14
Debug2 was produced while still 9600 bps......rc1 behaves very much the same as my very first rc installation.

**Comment by zarath** [comment] 2020-07-15 15:17
rc2 is on the way.. but you'll get a special extra version

**Comment by PA3CCE** [comment] 2020-07-15 15:19
OK, I'm waiting.

**Comment by zarath** [comment] 2020-07-15 15:21
bps doesn't matter on usb ACM serials... it's a virtual value from the past

**Comment by PA3CCE** [comment] 2020-07-15 15:23
OK

**Comment by PA3CCE** [comment] 2020-07-15 15:35
Well dinner is ready, I need a short break while you are doing the new versions, ok ?

**Comment by zarath** [comment] 2020-07-15 15:36
hope github is ok then... currently actions are degraded and don't build that binary

**Comment by PA3CCE** [comment] 2020-07-15 16:35
Ok, I'm back, is github working again ?

**Comment by PA3CCE** [comment] 2020-07-15 17:14
Congratulations, I started the program from commandline it started up, could connect, sweeprange was set to 50k-900MHz 1 segment ,,,,It ran correctly with reasonable result,......Did many things, set sweeprange to 50M  to 2G, set to 10 segments, set display to S21 gain, loaded the cal file from version 3.4.....All went flawlesly..... Just after setting " liines" iso "points" the trace remained  with points.....WILL DO SOME MORE TESTS BUT FOR NOW IT LOOKS ALL OK......thank you so much.

**Comment by zarath** [comment] 2020-07-15 17:17
phou.......

and please give me a debug.txt.... i need to know if my timing expectations with different bandwidth would be right...

**Comment by PA3CCE** [comment] 2020-07-15 17:37
OK, The program started up with the previous settings.....The sweep was a BiasTee from 50MHz to 2G, with 3dB att at CH0 and 10dB att at CH1 using the calibration file.
[debug4.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4926900/debug4.txt)

**Comment by PA3CCE** [comment] 2020-07-15 17:42
Started op with the previuous settings, but segments was reset to 1 after making the connection.

**Comment by PA3CCE** [comment] 2020-07-15 17:49
started from Windows,.... started up with blank Start/Stop and 1 sgement after connection Start/Stop previous settings but Segments remains at 1 , not set at 10.

**Comment by zarath** [comment] 2020-07-15 17:49
> Started op with the previuous settings, but segments was reset to 1 after making the connection.

that's intended on connection, to get a fast first sweep.
I see more benefits in getting feedback if device is ok, instead of waiting long and then to see something is wrong.

Perhaps a feature request for saving all states is a good idea...

as i told i reset bandwith also.. but if one want to call back all settings for a measurement, that would be a good idea...
(something like bandwidth, number of points, averages, calibration and so on)

but i close this bug now.
it already far to long!

Thanks for your patience and don't be frustrated.

**Comment by PA3CCE** [comment] 2020-07-15 17:52
Ok, I just was kidding HI, yes closed this session.

**Closed** 2020-07-15 17:51 UTC
