### ISSUE TITLE
communication error (ERROR - expected xx bytes, got yy) when using nanovna V2 with Saver

### ISSUE THREAD

**Issue by ok1vaw** [NanoVNA-Saver/nanovna-saver#323] opened 2020-08-21 09:27 UTC
**Describe the bug**
in the Python screen there are errors ERROR - expected xx bytes, got yy, on the graphs there are erratic information displayed or the Saver freezes.
**To Reproduce**
use NanoVNA V2, set sweep 20 to 120MHz, 101 points 10 segments
in black report python window or in debug txt there appears ERROR - expected xx bytes, got yy (xx, yy numbers). When this error appears, the data become erratic or the whole connection to V2 is lost.

**Expected behavior**
Work without error
**Screenshots**

**Desktop (please complete the following information):**
Win 10
 - Python version: [if applicable]
 - NanoVNA-Saver version: [e.g. 0.1.4] 0.3.7

**Additional context**
attached debug txt and screenshot
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/5107982/debug.txt)
![blackscreen1](https://user-images.githubusercontent.com/6250023/90875307-3d8b4a80-e3a1-11ea-90fc-e513e25e952e.jpg)

**Comment by ok1vaw** [comment] 2020-08-25 05:27
Can somebody inform about the correct driver for windows 10 for the V2? Is still the Cypress driver from 2015 the best one?

**Comment by ok1vaw** [comment] 2020-09-12 22:31
I have tested the changes, but still in a period about 1hr the same error appears, so it is still not fully removed. Mostly visible when selecting 51points, frequency 2 to 160MHz.

**Comment by ok1vaw** [comment] 2020-09-29 20:08
Still present with the newest firmware nanovna-v2-20200926-v2_2.bin. The period is the same, about 1time/hour. The Nanovna-Saver freezes, the NanoVNA V2 freezes too. The only way is to switch off the NanoVNA V2, then the Nanovna-Saver crashes.

**Comment by zarath** [comment] 2020-10-03 12:05
Should be fixed in latest v0.3.8-pre

**Comment by ok1vaw** [comment] 2020-10-04 12:10
Is the v0.3.8-pre version downloadable  for testing?

**Comment by ok1vaw** [comment] 2020-10-04 12:12
I saw a new fork for NanoVNA-Saver with NanoVNA V2, but there is no possibility to add issues. I think it would be practical to collect all issues with NanoVNA Saver with V2 to this place.

**Comment by zarath** [comment] 2020-10-04 12:50
Pre source downloadable as source (testing branch) . For binaries look at the Actions tab.

**Comment by ok1vaw** [comment] 2020-10-11 11:50
I have tested it with 0.3.8 . After certain time (minute to hour) the NanoVna-Saver crashes too, but now with error division by zero. See the listing from the end of the debug.txt:

2020-10-10 22:38:23,758 - NanoVNASaver.Settings.Sweep - DEBUG - get_index_range(0) -> (50000, 360000000)
2020-10-10 22:38:23,758 - NanoVNASaver.SweepWorker - INFO - Reading from 50000 to 360000000. Averaging 1 values
2020-10-10 22:38:23,760 - NanoVNASaver.SweepWorker - DEBUG - Reading average no 1 / 1
2020-10-10 22:38:23,760 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 50000 to 360000000
2020-10-10 22:38:23,760 - NanoVNASaver.SweepWorker - DEBUG - Read 101 frequencies
2020-10-10 22:38:23,760 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0
2020-10-10 22:38:23,902 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - reading values
2020-10-10 22:38:25,048 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index from: 20
2020-10-10 22:38:25,049 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index to: 19
2020-10-10 22:38:25,051 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:25,052 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1
2020-10-10 22:38:25,052 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:25,053 - NanoVNASaver.SweepWorker - DEBUG - Averaging 1 values
2020-10-10 22:38:25,056 - NanoVNASaver.SweepWorker - DEBUG - Calculating data and inserting in existing data at index 0
2020-10-10 22:38:25,085 - NanoVNASaver.SweepWorker - DEBUG - update Freqs: 101, Offset: 0
2020-10-10 22:38:25,085 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)
2020-10-10 22:38:25,085 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal
2020-10-10 22:38:25,085 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0
2020-10-10 22:38:25,085 - NanoVNASaver.Settings.Sweep - DEBUG - get_index_range(0) -> (50000, 360000000)
2020-10-10 22:38:25,085 - NanoVNASaver.SweepWorker - INFO - Reading from 50000 to 360000000. Averaging 1 values
2020-10-10 22:38:25,085 - NanoVNASaver.SweepWorker - DEBUG - Reading average no 1 / 1
2020-10-10 22:38:25,086 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 50000 to 360000000
2020-10-10 22:38:25,086 - NanoVNASaver.SweepWorker - DEBUG - Read 101 frequencies
2020-10-10 22:38:25,086 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0
2020-10-10 22:38:25,229 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - reading values
2020-10-10 22:38:26,382 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index from: 28
2020-10-10 22:38:26,382 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index to: 27
2020-10-10 22:38:26,385 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:26,385 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1
2020-10-10 22:38:26,386 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:26,386 - NanoVNASaver.SweepWorker - DEBUG - Averaging 1 values
2020-10-10 22:38:26,386 - NanoVNASaver.SweepWorker - DEBUG - Calculating data and inserting in existing data at index 0
2020-10-10 22:38:26,416 - NanoVNASaver.SweepWorker - DEBUG - update Freqs: 101, Offset: 0
2020-10-10 22:38:26,417 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)
2020-10-10 22:38:26,417 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal
2020-10-10 22:38:26,417 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0
2020-10-10 22:38:26,417 - NanoVNASaver.Settings.Sweep - DEBUG - get_index_range(0) -> (50000, 360000000)
2020-10-10 22:38:26,417 - NanoVNASaver.SweepWorker - INFO - Reading from 50000 to 360000000. Averaging 1 values
2020-10-10 22:38:26,417 - NanoVNASaver.SweepWorker - DEBUG - Reading average no 1 / 1
2020-10-10 22:38:26,417 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 50000 to 360000000
2020-10-10 22:38:26,418 - NanoVNASaver.SweepWorker - DEBUG - Read 101 frequencies
2020-10-10 22:38:26,418 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0
2020-10-10 22:38:26,565 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - reading values
2020-10-10 22:38:27,696 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index from: 31
2020-10-10 22:38:27,696 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index to: 30
2020-10-10 22:38:27,698 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:27,699 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1
2020-10-10 22:38:27,699 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:27,700 - NanoVNASaver.SweepWorker - DEBUG - Averaging 1 values
2020-10-10 22:38:27,703 - NanoVNASaver.SweepWorker - DEBUG - Calculating data and inserting in existing data at index 0
2020-10-10 22:38:27,731 - NanoVNASaver.SweepWorker - DEBUG - update Freqs: 101, Offset: 0
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0
2020-10-10 22:38:27,732 - NanoVNASaver.Settings.Sweep - DEBUG - get_index_range(0) -> (50000, 360000000)
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - INFO - Reading from 50000 to 360000000. Averaging 1 values
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Reading average no 1 / 1
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 50000 to 360000000
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Read 101 frequencies
2020-10-10 22:38:27,732 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0
2020-10-10 22:38:27,877 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - reading values
2020-10-10 22:38:29,035 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index from: 35
2020-10-10 22:38:29,035 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index to: 34
2020-10-10 22:38:29,038 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:29,038 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1
2020-10-10 22:38:29,038 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:29,039 - NanoVNASaver.SweepWorker - DEBUG - Averaging 1 values
2020-10-10 22:38:29,042 - NanoVNASaver.SweepWorker - DEBUG - Calculating data and inserting in existing data at index 0
2020-10-10 22:38:29,070 - NanoVNASaver.SweepWorker - DEBUG - update Freqs: 101, Offset: 0
2020-10-10 22:38:29,070 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)
2020-10-10 22:38:29,070 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal
2020-10-10 22:38:29,070 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0
2020-10-10 22:38:29,071 - NanoVNASaver.Settings.Sweep - DEBUG - get_index_range(0) -> (50000, 360000000)
2020-10-10 22:38:29,071 - NanoVNASaver.SweepWorker - INFO - Reading from 50000 to 360000000. Averaging 1 values
2020-10-10 22:38:29,071 - NanoVNASaver.SweepWorker - DEBUG - Reading average no 1 / 1
2020-10-10 22:38:29,071 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 50000 to 360000000
2020-10-10 22:38:29,071 - NanoVNASaver.SweepWorker - DEBUG - Read 101 frequencies
2020-10-10 22:38:29,071 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0
2020-10-10 22:38:29,214 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - reading values
2020-10-10 22:38:30,364 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index from: 39
2020-10-10 22:38:30,364 - NanoVNASaver.Hardware.NanoVNA_V2 - DEBUG - Freq index to: 38
2020-10-10 22:38:30,367 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:30,368 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1
2020-10-10 22:38:30,368 - NanoVNASaver.SweepWorker - DEBUG - Read 101 values
2020-10-10 22:38:30,369 - NanoVNASaver.SweepWorker - DEBUG - Averaging 1 values
2020-10-10 22:38:30,369 - NanoVNASaver.SweepWorker - DEBUG - Calculating data and inserting in existing data at index 0
2020-10-10 22:38:30,399 - NanoVNASaver.SweepWorker - DEBUG - update Freqs: 101, Offset: 0
2020-10-10 22:38:30,399 - NanoVNASaver.SweepWorker - DEBUG - Saving data to application (101 and 101 points)
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - DEBUG - Sending "updated" signal
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - DEBUG - Sweep segment no 0
2020-10-10 22:38:30,400 - NanoVNASaver.Settings.Sweep - DEBUG - get_index_range(0) -> (50000, 360000000)
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - INFO - Reading from 50000 to 360000000. Averaging 1 values
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - DEBUG - Reading average no 1 / 1
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - DEBUG - Setting sweep range to 50000 to 360000000
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - DEBUG - Read 101 frequencies
2020-10-10 22:38:30,400 - NanoVNASaver.SweepWorker - DEBUG - Reading data 0
2020-10-10 22:38:30,533 - NanoVNASaver.Hardware.NanoVNA_V2 - INFO - reading values
2020-10-10 22:38:34,266 - NanoVNASaver.Hardware.NanoVNA_V2 - WARNING - expected 3264 bytes, got 0
2020-10-10 22:38:37,936 - NanoVNASaver.SweepWorker - DEBUG - Read 0 values
2020-10-10 22:38:37,936 - NanoVNASaver.SweepWorker - DEBUG - Reading data 1
2020-10-10 22:38:37,936 - NanoVNASaver.SweepWorker - DEBUG - Read 102 values
2020-10-10 22:38:37,936 - NanoVNASaver.SweepWorker - INFO - No valid data during this run
2020-10-10 22:38:37,936 - NanoVNASaver.SweepWorker - DEBUG - Averaging 1 values
2020-10-10 22:38:37,937 - NanoVNASaver.SweepWorker - ERROR - division by zero
Traceback (most recent call last):
  File "C:\.......\nanovna-saver-0.3.8-pre\NanoVNASaver\SweepWorker.py", line 80, in run
    self._run()
  File "C:\.......\nanovna-saver-0.3.8-pre\NanoVNASaver\SweepWorker.py", line 121, in _run
    freq, values11, values21 = self.readAveragedSegment(
  File "C:\.......\nanovna-saver-0.3.8-pre\NanoVNASaver\SweepWorker.py", line 253, in readAveragedSegment
    values11 = np.average(values11, 0).tolist()
  File "<__array_function__ internals>", line 5, in average
  File "C:\.......\lib\site-packages\numpy\lib\function_base.py", line 394, in average
    scl = avg.dtype.type(a.size/avg.size)
ZeroDivisionError: division by zero
2020-10-10 22:39:23,605 - NanoVNASaver.Hardware.VNA - INFO - disconnect COM10 (S-A-A-2)
2020-10-10 22:39:23,656 - NanoVNASaver.Hardware.VNA - INFO - connect COM10 (S-A-A-2)

**Comment by zarath** [comment] 2020-10-11 12:21
Again an error during communication... not a bug in Nanovna-saver, but at least I can try to catch it, so it wouldn't crash at least

**Comment by ok1vaw** [comment] 2020-10-11 16:03
Unfortunatelly after confirming the division by zero by pressing the button the Saver can not continue and freezes and must be closed and restarted.

**Comment by DG9BFC** [comment] 2020-10-13 14:19
when i press button on device on constant sweep i got an error ... when i press the button while in "pause" (connected but sweep fnished) it reconnects when i press sweep button (but that sweep shows different values so ANOTHER press is needed to have a clean sweep)
at least it does not die or needs a restart ... so in my view its ok 
easy solution ... do not press button while in pc mode ... grin

**Comment by ok1vaw** [comment] 2020-10-13 19:05
I meant the  **virtual button** on the PC screen, not about any button on the V2. Try to keep sweeping from 1MHz to 160MHz continuous for few minutes and I am curious if you got the same results with the division by zero error.

**Comment by DG9BFC** [comment] 2020-10-13 20:40
ok ok ... missunderstood ... no problem :-)

**Closed** 2020-11-01 13:21 UTC
Labels: bug
