### ISSUE TITLE
NanoVNA-Saver 0.3.7 rc3 Marker frequencies are divided by number of segments.

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#304] opened 2020-07-31 19:25 UTC
**Describe the bug**

When I start NanoVNA-Saver 0.3.7 rc3 from command window It starts up with empty frequency bars that's OK , when I press "Connect to Device" the Start/Stop frequency  is set to the latest used values, and **all** the marker fields are filled with frequencies devided equally over the frequency span, thats **vy** fine,.... Segments setting is still at 1, ...  Now when I set segments to 2 , all marker frequencies are devide by 2 etc. (rounded)

IMHO Marker frequencies shall not be **number of segments** dependant.

**Comment by zarath** [comment] 2020-07-31 20:26
Duplicate of #303

**Closed by zarath** 2020-07-31 20:26 UTC
