### ISSUE TITLE
NanoVNASaver 0.4.0 Trackback Error

### ISSUE THREAD

**Issue by mikidawizz** [NanoVNA-Saver/nanovna-saver#532] opened 2022-08-31 13:40 UTC
HI,
I get an error on the odd occasion when starting nanosaver,
I have attached a screen shot of the issue.

Regards,
Miki
![Screenshot 2022-08-31 230948](https://user-images.githubusercontent.com/54282464/187692375-3e527382-419a-48bd-93cc-59b2c92d949f.png)

**Comment by kschmahl** [comment] 2022-08-31 17:56
I've seen that as well.
It was a couple months ago, but I believe it was caused by attempts to plot Smith charts.  I disabled the plots, perhaps by editing the config file.  I work mostly in S-parameters, which worked well enough.

**Comment by zarath** [comment] 2022-09-20 05:50
Problem occurs with python 3.10.
Fixed in v0.5.3

**Closed by zarath** 2022-09-20 05:50 UTC
Labels: bug

**Comment by mikidawizz** [comment] 2022-09-25 12:42
Thank You... :-)
